### ISSUE TITLE
Ensure no extra columns display in the listing.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/query-overview#153]
i.e. make sure the number of columns matches the number of headers

# Test notes
* Download the cat dataset, add a column with the header "open_time", fill its cells with some string, and upload the updated dataset to cat.
* Verify the listing has one header per column - no columns should be missing a header
* Verify that the "Query Recency" Filter only has the string you added in the cells of the open_time column in it.

**Comment by pburnsdata** [comment]
I'm guessing that in Heather's situation, there was a column of data that didn't have a header. Going to update it to drop columns that lack headers and print a warning to the console.

**Comment by pburnsdata** [comment]
No longer dropping headerless columns, per Spencer: "In RhoMAP, the dataset already has a query recency column, so two columns with the same header (Query Recency) were causing the trouble here. Since the derived query recency variable is set to the provided query recency variable, we don't need both to appear in the listing."

**Comment by dschwentker** [comment]
Tested and passed
